server:
    port: 8081
    shutdown: GRACEFUL

spring:
    application:
        name: catalog-service
    datasource:
        url: ${DB_URL:jdbc:postgresql://localhost:15432/postgres}
        username: ${DB_USERNAME:postgres}
        password: ${DB_PASSWORD:postgres}
    jpa:
        open-in-view: false

management:
    endpoints:
        web:
            exposure:
                include:
                    - '*'
    info:
        git:
            mode: FULL