name: 'books-store-microservices'
services:
    catalog-db:
        image: postgres:17-alpine
        container_name: catalog-db
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        ports:
            - "15432:5432"
        volumes:
            - catalog-data:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 10s
            timeout: 5s
            retries: 5
        deploy:
            resources:
                limits:
                    memory: 500m

    order-db:
        image: postgres:17-alpine
        container_name: order-db
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        ports:
            - "25432:5432"
        volumes:
            - order-data:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 10s
            timeout: 5s
            retries: 5
        deploy:
            resources:
                limits:
                    memory: 500m

    notification-db:
        image: postgres:17-alpine
        container_name: notification-db
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        ports:
            - "35432:5432"
        volumes:
            - notification-data:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 10s
            timeout: 5s
            retries: 5
        deploy:
            resources:
                limits:
                    memory: 500m

    bookstore-rabbitmq:
        image: rabbitmq:4.0.4-management-alpine
        container_name: bookstore-rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - bookstore-rabbitmq-data:/var/lib/rabbitmq
        healthcheck:
            test: rabbitmq-diagnostics check_port_connectivity
            interval: 30s
            timeout: 30s
            retries: 10
        deploy:
            resources:
                limits:
                    memory: 500m

    mailhog:
        image: mailhog/mailhog:v1.0.1
        container_name: mailhog
        ports:
            - "1025:1025"
            - "8025:8025"

    keycloak:
        image: quay.io/keycloak/keycloak:24.0.2
        command: [ 'start-dev', '--import-realm', '--http-port=9191' ]
        container_name: keycloak
        hostname: keycloak
        volumes:
            - ./realm-config:/opt/keycloak/data/import
        environment:
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=admin1234
        ports:
            - "9191:9191"
        deploy:
            resources:
                limits:
                    memory: 2gb

volumes:
    catalog-data:
    order-data:
    notification-data:
    bookstore-rabbitmq-data: