server:
    port: 8082
    shutdown: GRACEFUL

spring:
    application:
        name: order-service
    datasource:
        url: ${DB_URL:jdbc:postgresql://localhost:25432/postgres}
        username: ${DB_USERNAME:postgres}
        password: ${DB_PASSWORD:postgres}
    jpa:
        open-in-view: false
    rabbitmq:
        host: ${RABBITMQ_HOST:localhost}
        port: ${RABBITMQ_PORT:5672}
        username: ${RABBITMQ_USERNAME:guest}
        password: ${RABBITMQ_PASSWORD:guest}

management:
    endpoints:
        web:
            exposure:
                include:
                    - '*'
    info:
        git:
            mode: FULL

orders:
    catalog-service-url: http://localhost:8081
    order-events-exchange: "orders-exchange"
    new-orders-queue: "new-orders"
    delivered-orders-queue: "delivered-orders"
    cancelled-orders-queue: "cancelled-orders"
    error-orders-queue: "error-orders"
